### ISSUE TITLE
NCAA Website

### ISSUE THREAD

**Issue by emswann** [emswann/recruitlete#6]
Verify access to NCAA website to get college information.

**Comment by dentonkerr** [comment]
http://web1.ncaa.org/onlineDir/exec2/sponsorship?sortOrder=0&division=1&sport=WVB  = D1

http://web1.ncaa.org/onlineDir/exec2/sponsorship?sortOrder=0&division=2&sport=WVB  = D2

http://web1.ncaa.org/onlineDir/exec2/sponsorship?sortOrder=0&division=3&sport=WVB  = D3
